project_id = "giprsjtilgbemsiwtjkx"

[functions.sync-processes]
verify_jwt = true

[functions.sync-distributions]
verify_jwt = true

[functions.manage-publication-terms]
verify_jwt = true

[functions.sync-publications]
verify_jwt = true

[functions.sync-orchestrator]
verify_jwt = true