project_id = "giprsjtilgbemsiwtjkx"

[functions.sync-processes]
verify_jwt = true

[functions.sync-distributions]
verify_jwt = true

[functions.manage-publication-terms]
verify_jwt = true

[functions.sync-publications]
verify_jwt = true

[functions.sync-orchestrator]
verify_jwt = true

[functions.api-processes]
verify_jwt = false

[functions.api-distributions]
verify_jwt = false

[functions.api-publications]
verify_jwt = false

[functions.api-webhook]
verify_jwt = true

[functions.sync-process-management]
verify_jwt = true

[functions.sync-process-updates]
verify_jwt = true

[functions.manage-distribution-terms]
verify_jwt = true
